version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - todo-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/todos
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - todo-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - todo-network

volumes:
  mongodb-data:

networks:
  todo-network:
    driver: bridge
